line_length: 
- 192 # warning
- 256 # error
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
 - JobFair/API.swift
 - JobFairTests/
disabled_rules:
 - trailing_whitespace
 - identifier_name